server:
  port: 18081

spring:
  application:
    name: 01-HelloWorld
  config:
    import: optional:classpath:application-local.yml

agentscope:
  model:
    provider: dashscope
  dashscope:
    model-name: qwen-plus
    stream: true
